export const VERSION = '0.0.0';
export * from './config/schema.js';
export * from './config/loader.js';
export * from './store/index.js';
export * from './plugin/index.js';
export * from './auth/index.js';
export * from './seed/index.js';
export * from './bdd/index.js';
export * from './runner/index.js';
export * from './contract/index.js';
export * from './tests/index.js';
