/**
 * Unit tests for — surgical yarn.lock entry removal.
 *
 * AC-1: the override resolves transitively — proven by showing the target
 * package's block(s) are removed from both a classic yarn.lock and a Berry
 * (`__metadata:`) yarn.lock, including multi-descriptor and scoped-package
 * blocks, while every other block is left byte-for-byte unchanged.
 */

import { describe, it, expect } from 'vitest';
import { pruneYarnLockEntry } from './pruneYarnLock.mjs';

// ---------------------------------------------------------------------------
// Classic-style yarn.lock fixture: plain-name blocks, a multi-descriptor
// block, and a scoped-package block.
// ---------------------------------------------------------------------------
const classicLockfile = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"lodash@^4.0.0", "lodash@4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-old-lodash-hash

foo@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz"
  integrity sha512-foo-hash

"@scope/name@^1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/@scope/name/-/name-1.0.0.tgz"
  integrity sha512-scope-name-hash
`;

describe('AC-1: pruneYarnLockEntry — classic yarn.lock', () => {
  it('removes a block with multiple comma-separated descriptors for the target', () => {
    const result = pruneYarnLockEntry(classicLockfile, 'lodash');
    expect(result).not.toContain('lodash@^4.0.0');
    expect(result).not.toContain('sha512-old-lodash-hash');
  });

  it('leaves every other block byte-for-byte unchanged', () => {
    const result = pruneYarnLockEntry(classicLockfile, 'lodash');
    expect(result).toContain(
      'foo@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/foo/-/foo-1.0.0.tgz"\n  integrity sha512-foo-hash',
    );
    expect(result).toContain('sha512-scope-name-hash');
  });

  it('correctly matches and removes a scoped package, not an unscoped lookalike', () => {
    const result = pruneYarnLockEntry(classicLockfile, '@scope/name');
    expect(result).not.toContain('sha512-scope-name-hash');
    expect(result).toContain('sha512-foo-hash');
    expect(result).toContain('sha512-old-lodash-hash');
  });

  it('preserves the header comment lines', () => {
    const result = pruneYarnLockEntry(classicLockfile, 'lodash');
    expect(result).toContain('# THIS IS AN AUTOGENERATED FILE');
    expect(result).toContain('# yarn lockfile v1');
  });
});

// ---------------------------------------------------------------------------
// Berry-style yarn.lock fixture: leading __metadata: block plus
// languageName:/linkType: fields inside package blocks.
// ---------------------------------------------------------------------------
const berryLockfile = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21, lodash@npm:4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: old-lodash-checksum
  languageName: node
  linkType: hard

"foo@npm:^1.0.0":
  version: 1.0.0
  resolution: "foo@npm:1.0.0"
  checksum: foo-checksum
  languageName: node
  linkType: hard

"@scope/name@npm:^1.0.0":
  version: 1.0.0
  resolution: "@scope/name@npm:1.0.0"
  checksum: scope-name-checksum
  languageName: node
  linkType: hard
`;

describe('AC-1: pruneYarnLockEntry — Berry yarn.lock', () => {
  it('removes the target package block', () => {
    const result = pruneYarnLockEntry(berryLockfile, 'lodash');
    expect(result).not.toContain('old-lodash-checksum');
  });

  it('never touches the __metadata: header block', () => {
    const result = pruneYarnLockEntry(berryLockfile, 'lodash');
    expect(result).toContain('__metadata:');
    expect(result).toContain('cacheKey: 10c0');
  });

  it('leaves every other block byte-for-byte unchanged', () => {
    const result = pruneYarnLockEntry(berryLockfile, 'lodash');
    expect(result).toContain('foo-checksum');
    expect(result).toContain('scope-name-checksum');
    expect(result).toContain('languageName: node');
  });

  it('matches scoped descriptors using the npm: protocol form correctly', () => {
    const result = pruneYarnLockEntry(berryLockfile, '@scope/name');
    expect(result).not.toContain('scope-name-checksum');
    expect(result).toContain('foo-checksum');
    expect(result).toContain('old-lodash-checksum');
  });
});
